### ISSUE TITLE
Using config files on Windows requires setting env variables

### ISSUE THREAD

**Issue by demilich1** [solidiquis/erdtree#152]
The documentation mentions how `erdtree` locates user-created config files:

> erdtree will look for a configuration file in any of these locations:
> 
>     - $ERDTREE_CONFIG_PATH
>     - $XDG_CONFIG_HOME/erdtree/.erdtreerc
>     - $XDG_CONFIG_HOME/.erdtreerc
>     - $HOME/.config/erdtree/.erdtreerc
>     - $HOME/.erdtreerc

However all of those environment variables are not set by default on Windows. I would expect that `$HOME/.config/erdtree/.erdtreerc` resolves to `%HOME%\erdtree\.erdtreerc`. This does not seem to be the case; I actually had to create a new env variable called `$HOME` pointing to `C:\Users\$MY_WINDOWS_LOGIN\` and then it worked.

Suggestion: Use `%HOME%` on Windows instead of `$HOME` when locating config files.

**Comment by solidiquis** [comment]
Interesting. Thank you for pointing this out. I will have this addressed.

**Comment by demilich1** [comment]
Would you accept a PR for this issue or do you want to tackle it yourself? In the first case I would give it a shot

**Comment by solidiquis** [comment]
@demilich1 Sure! More than happy to accept a PR. Instead of `%HOME%` however I'd advocate for `%APPDATA%` as that is the conventional directory on Windows used to store user specific configurations related to a program. It's something I forgot to consider initially. So essentially the full path to the configuration file should be:

```
%APPDATA%\erdtree\.erdtreerc
```

For your convenience, here is the file you're likely to touch: `src/render/context/config.rs`

The unit test for reading in the configuration file can be found at: `src/render/context/test.rs`

I'm not sure if what you're doing warrants additional testing but I'll leave that up to you to decide. If you wouldn't mind updating the README.md as well too that'd be great!
