### ISSUE TITLE
error when running V3.1.2

### ISSUE THREAD

**Issue by ixzh** [solidiquis/erdtree#222]
I have the following error when running erd:

error: unexpected argument '--size-left' found

P.S.: I found another et app in ~/.cargo/bin folder. Since when erdtree renamed to erd? How can I uninstall older version?

**Comment by solidiquis** [comment]
Hello! So you must have missed a few releases.

`et` -> `erd` when `v2.0` was released due to [name collisions](https://github.com/solidiquis/erdtree/issues/23) with some Linux packages.

`--size-left` has since been deprecated and is no longer necessary. Size is now displayed on the left only.

Please check to see if you have a `.erdtreerc` file. You might have `--size-left` specified in there. Here's a link on how to get [setup with the new configurations](https://github.com/solidiquis/erdtree#configuration-file).

To get the latest erdtree version you can just: `$ cargo install erdtree`.

If that doesn't work for whatever reason why `$ cargo uninstall erdtree` then `$ cargo install erdtree`.

Let me know if you have any persistent issues!

**Comment by ixzh** [comment]
> Please check to see if you have a `.erdtreerc` file.

You are right. I have that line in the hidden config in `~/..config/erdtree/.erdtreerc`. It works after removing it.
